- project:
    templates:
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - python-tempestconf-tempest-devstack-admin
        - python-tempestconf-tempest-devstack-admin-train
        - python-tempestconf-tempest-devstack-admin-stein
        - python-tempestconf-tempest-devstack-admin-rocky
        - python-tempestconf-tempest-devstack-admin-queens
        - python-tempestconf-tempest-devstack-admin-py3
        - python-tempestconf-tempest-devstack-demo
        - python-tempestconf-tempest-devstack-demo-py3
        - python-tempestconf-tempest-packstack-admin:
            voting: false
        - python-tempestconf-tempest-packstack-demo:
            voting: false
        - python-tempestconf-tempest-devstack-admin-plugins
        - tripleo-ci-centos-7-scenario002-standalone
        - tripleo-ci-centos-7-standalone
        - refstack-client-devstack-tempestconf
    gate:
      jobs:
        - python-tempestconf-tempest-devstack-admin
        - python-tempestconf-tempest-devstack-admin-train
        - python-tempestconf-tempest-devstack-admin-stein
        - python-tempestconf-tempest-devstack-admin-rocky
        - python-tempestconf-tempest-devstack-admin-queens
        - python-tempestconf-tempest-devstack-admin-py3
        - python-tempestconf-tempest-devstack-demo
        - python-tempestconf-tempest-devstack-demo-py3
        - python-tempestconf-tempest-packstack-admin:
            voting: false
        - python-tempestconf-tempest-packstack-demo:
            voting: false
        - python-tempestconf-tempest-devstack-admin-plugins
        - tripleo-ci-centos-7-scenario002-standalone
        - tripleo-ci-centos-7-standalone
        - refstack-client-devstack-tempestconf
    experimental:
      jobs:
        - python-tempestconf-tempest-devstack-demo-train
        - python-tempestconf-tempest-devstack-demo-stein
        - python-tempestconf-tempest-devstack-demo-rocky
        - python-tempestconf-tempest-devstack-demo-queens


- job:
    name: python-tempestconf-devstack-base
    parent: devstack
    description: Base job for python-tempestconf on a devstack environment
    required-projects:
      - openstack/heat
      - openstack/heat-tempest-plugin
      - openstack/manila
      - openstack/manila-ui
      - openstack/manila-tempest-plugin
      - openstack/python-tempestconf
      - openstack/tempest
      - openstack/devstack
      - openstack/designate
      - openstack/designate-tempest-plugin
    roles:
      - zuul: openstack/python-tempestconf
      - zuul: openstack/tempest
      - zuul: openstack/devstack
    vars:
      zuul_copy_output:
        '{{ devstack_base_dir }}/tempest/tempest.log': logs
        '{{ devstack_base_dir }}/tempest/etc/tempest.conf': logs
        '{{ zuul.project.src_dir }}/etc/accounts.yaml': logs
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
        manila: https://opendev.org/openstack/manila
        manila-ui: https://opendev.org/openstack/manila-ui
        designate: https://opendev.org/openstack/designate
      devstack_localrc:
        MANILA_USE_UWSGI: False
        MANILA_USE_MOD_WSGI: False
      devstack_services:
        h-eng: True
        h-api: True
        h-api-cfn: True
        h-api-cw: True
        designate: True
        designate-central: True
        designate-api: True
        designate-worker: True
        designate-producer: True
        designate-mdns: True
    irrelevant-files:
      - config_tempest/tests/.*$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^.*\.rst$

- job:
    name: python-tempestconf-packstack-base
    parent: packstack-allinone
    description: Base job for python-tempestconf on packstack environment
    required-projects:
      - x/packstack
      - openstack/python-tempestconf
      - openstack/tempest
      - openstack/devstack
    post-run: playbooks/upload-logs.yaml
    roles:
      - zuul: x/packstack
      - zuul: openstack/python-tempestconf
      - zuul: openstack/tempest
      - zuul: openstack/devstack
    vars:
      tempest_concurrency: 2
      scenario: scenario000
      zuul_copy_output:
        /opt/stack/tempest/etc/tempest.conf: logs
        /opt/stack/tempest/tempest.log: logs
        /etc/openstack/accounts.yaml: logs
    irrelevant-files:
      - config_tempest/tests/.*$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^.*\.rst$

- job:
    name: python-tempestconf-tempest-devstack-admin-plugins
    parent: python-tempestconf-devstack-base
    description: |
      Tempest job for python-tempestconf on a devstack environment as the admin user.
    run: playbooks/python-tempestconf-tempest-devstack.yaml
    vars:
      test_regex:
        - 'heat_tempest_plugin'
        - 'designate_tempest_plugin'
      black_regex:
        - 'heat_tempest_plugin.tests.scenario.test_volumes.VolumeBackupRestoreIntegrationTest.test_cinder_volume_create_backup_restore'
        - 'heat_tempest_plugin.tests.scenario.test_server_software_config.SoftwareConfigIntegrationTest.test_server_software_config'
        - 'heat_tempest_plugin.tests.scenario.test_server_signal.ServerSignalIntegrationTest.test_server_signal_userdata_format_software_config'
        - 'heat_tempest_plugin.tests.scenario.test_aodh_alarm.AodhAlarmTest.test_alarm'
        - 'heat_tempest_plugin.tests.scenario.test_server_cfn_init.CfnInitIntegrationTest.test_server_cfn_init'
        - 'heat_tempest_plugin.tests.scenario.test_base_resources.BasicResourcesTest.test_base_resources_integration'
        - 'heat_tempest_plugin.tests.functional.test_os_wait_condition.OSWaitCondition.test_create_stack_with_multi_signal_waitcondition'
      user: admin
      cloud_user: devstack-admin
      plugins_paths:
        - "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/heat-tempest-plugin'].src_dir }}"
        - "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/designate-tempest-plugin'].src_dir }}"
      tempest_concurrency: 2

- job:
    name: python-tempestconf-tempest-devstack-admin
    parent: python-tempestconf-devstack-base
    description: |
      Tempest job for python-tempestconf on a devstack environment as the admin user.
    run: playbooks/python-tempestconf-tempest-devstack.yaml
    vars:
      user: admin
      cloud_user: devstack-admin
      tempest_concurrency: 2

- job:
    name: python-tempestconf-tempest-devstack-admin-train
    parent: python-tempestconf-tempest-devstack-admin
    override-checkout: stable/train
    vars:
      branch: stable/train

- job:
    name: python-tempestconf-tempest-devstack-admin-stein
    parent: python-tempestconf-tempest-devstack-admin
    override-checkout: stable/stein
    vars:
      branch: stable/stein

- job:
    name: python-tempestconf-tempest-devstack-admin-rocky
    parent: python-tempestconf-tempest-devstack-admin
    override-checkout: stable/rocky
    vars:
      branch: stable/rocky

- job:
    name: python-tempestconf-tempest-devstack-admin-queens
    parent: python-tempestconf-tempest-devstack-admin
    override-checkout: stable/queens
    vars:
      branch: stable/queens

- job:
    name: python-tempestconf-tempest-devstack-demo
    parent: python-tempestconf-devstack-base
    description: |
      Tempest job for python-tempestconf on a devstack environment as the demo user.
    run: playbooks/python-tempestconf-tempest-devstack.yaml
    vars:
      aditional_tempestconf_params: "auth.tempest_roles member"
      user: demo
      cloud_user: devstack
      test_demo: true
      cloud_admin: devstack-admin
      # concurrency is reduced in this job, because a minimal accounts
      # file is used
      tempest_concurrency: 1
      # skip until https://storyboard.openstack.org/#!/story/2004209
      # is resolved
      tempest_black_regex: 'tempest.api.compute.servers'

- job:
    name: python-tempestconf-tempest-devstack-demo-train
    parent: python-tempestconf-tempest-devstack-demo
    override-checkout: stable/train
    vars:
      branch: stable/train

- job:
    name: python-tempestconf-tempest-devstack-demo-stein
    parent: python-tempestconf-tempest-devstack-demo
    override-checkout: stable/stein
    vars:
      branch: stable/stein

- job:
    name: python-tempestconf-tempest-devstack-demo-rocky
    parent: python-tempestconf-tempest-devstack-demo
    override-checkout: stable/rocky
    vars:
      branch: stable/rocky

- job:
    name: python-tempestconf-tempest-devstack-demo-queens
    parent: python-tempestconf-tempest-devstack-demo
    override-checkout: stable/queens
    vars:
      branch: stable/queens

- job:
    name: python-tempestconf-tempest-packstack-admin
    parent: python-tempestconf-packstack-base
    description: |
      Tempest job for python-tempestconf on a packstack environment as the admin user.
    run: playbooks/python-tempestconf-tempest-packstack.yaml
    vars:
      user: admin

- job:
    name: python-tempestconf-tempest-packstack-demo
    parent: python-tempestconf-packstack-base
    description: |
      Tempest job for python-tempestconf on a packstack environment as the demo user.
    run: playbooks/python-tempestconf-tempest-packstack.yaml
    vars:
      user: demo
      test_demo: true
      cloud_admin: packstack-admin

- job:
    name: python-tempestconf-tempest-devstack-admin-py3
    parent: python-tempestconf-tempest-devstack-admin
    description: |
      Tempest job for python-tempestconf on a devstack environment with python3 enabled.
    vars:
      tempestconf_pip_virtualenv_python: "python3"
      devstack_localrc:
        USE_PYTHON3: true
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # without Swift, c-bak cannot run (in the Gate at least)
        c-bak: false

- job:
    name: python-tempestconf-tempest-devstack-demo-py3
    parent: python-tempestconf-tempest-devstack-demo
    description: |
      Tempest job for python-tempestconf on a devstack environment with python3 enabled
      for demo users.
    vars:
      aditional_tempestconf_params: "auth.tempest_roles member"
      tempestconf_pip_virtualenv_python: "python3"
      devstack_localrc:
        USE_PYTHON3: true
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # without Swift, c-bak cannot run (in the Gate at least)
        c-bak: false
