- project:
    templates:
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - python-tempestconf-tempest-devstack-admin
        - python-tempestconf-tempest-devstack-admin-py3
        - python-tempestconf-tempest-devstack-demo
        - python-tempestconf-tempest-devstack-demo-py3
        - python-tempestconf-tempest-packstack-admin
        - python-tempestconf-tempest-packstack-demo
        - tripleo-ci-centos-7-scenario002-standalone
        - tripleo-ci-centos-7-standalone-os-tempest
        - refstack-client-devstack-tempestconf
    gate:
      jobs:
        - python-tempestconf-tempest-devstack-admin
        - python-tempestconf-tempest-devstack-admin-py3
        - python-tempestconf-tempest-devstack-demo
        - python-tempestconf-tempest-devstack-demo-py3
        - python-tempestconf-tempest-packstack-admin
        - python-tempestconf-tempest-packstack-demo
        - tripleo-ci-centos-7-scenario002-standalone
        - tripleo-ci-centos-7-standalone-os-tempest
        - refstack-client-devstack-tempestconf

- job:
    name: python-tempestconf-devstack-base
    parent: devstack
    description: Base job for python-tempestconf on a devstack environment
    required-projects:
      - openstack/manila
      - openstack/manila-ui
      - openstack/manila-tempest-plugin
      - openstack/python-tempestconf
      - openstack/tempest
      - openstack/devstack
    roles:
      - zuul: openstack/python-tempestconf
      - zuul: openstack/tempest
      - zuul: openstack/devstack
    vars:
      zuul_copy_output:
        '{{ devstack_base_dir }}/tempest/tempest.log': logs
        '{{ devstack_base_dir }}/tempest/etc/tempest.conf': logs
        '{{ zuul.project.src_dir }}/etc/accounts.yaml': logs
      devstack_plugins:
        manila: https://opendev.org/openstack/manila
        manila-ui: https://opendev.org/openstack/manila-ui
      devstack_localrc:
        MANILA_USE_UWSGI: False
        MANILA_USE_MOD_WSGI: False
    irrelevant-files:
      - config_tempest/tests/.*$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^.*\.rst$

- job:
    name: python-tempestconf-packstack-base
    parent: packstack-allinone
    description: Base job for python-tempestconf on packstack environment
    required-projects:
      - x/packstack
      - openstack/python-tempestconf
      - openstack/tempest
      - openstack/devstack
    post-run: playbooks/upload-logs.yaml
    roles:
      - zuul: x/packstack
      - zuul: openstack/python-tempestconf
      - zuul: openstack/tempest
      - zuul: openstack/devstack
    vars:
      tempest_concurrency: 2
      scenario: scenario000
      zuul_copy_output:
        /opt/stack/tempest/etc/tempest.conf: logs
        /opt/stack/tempest/tempest.log: logs
        /etc/openstack/accounts.yaml: logs
    irrelevant-files:
      - config_tempest/tests/.*$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^.*\.rst$

- job:
    name: python-tempestconf-tempest-devstack-admin
    parent: python-tempestconf-devstack-base
    description: |
      Tempest job for python-tempestconf on a devstack environment as the admin user.
    run: playbooks/python-tempestconf-tempest-devstack.yaml
    vars:
      user: admin
      cloud_user: devstack-admin
      tempest_concurrency: 2

- job:
    name: python-tempestconf-tempest-devstack-demo
    parent: python-tempestconf-devstack-base
    description: |
      Tempest job for python-tempestconf on a devstack environment as the demo user.
    run: playbooks/python-tempestconf-tempest-devstack.yaml
    vars:
      aditional_tempestconf_params: "auth.tempest_roles member"
      user: demo
      cloud_user: devstack
      test_demo: true
      cloud_admin: devstack-admin
      # concurrency is reduced in this job, because a minimal accounts
      # file is used
      tempest_concurrency: 1
      # skip until https://storyboard.openstack.org/#!/story/2004209
      # is resolved
      tempest_black_regex: 'tempest.api.compute.servers'

- job:
    name: python-tempestconf-tempest-packstack-admin
    parent: python-tempestconf-packstack-base
    description: |
      Tempest job for python-tempestconf on a packstack environment as the admin user.
    run: playbooks/python-tempestconf-tempest-packstack.yaml
    vars:
      user: admin

- job:
    name: python-tempestconf-tempest-packstack-demo
    parent: python-tempestconf-packstack-base
    description: |
      Tempest job for python-tempestconf on a packstack environment as the demo user.
    run: playbooks/python-tempestconf-tempest-packstack.yaml
    vars:
      user: demo
      test_demo: true
      cloud_admin: packstack-admin

- job:
    name: python-tempestconf-tempest-devstack-admin-py3
    parent: python-tempestconf-tempest-devstack-admin
    description: |
      Tempest job for python-tempestconf on a devstack environment with python3 enabled.
    vars:
      tempestconf_pip_virtualenv_python: "python3"
      devstack_localrc:
        USE_PYTHON3: true
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # without Swift, c-bak cannot run (in the Gate at least)
        c-bak: false

- job:
    name: python-tempestconf-tempest-devstack-demo-py3
    parent: python-tempestconf-tempest-devstack-demo
    description: |
      Tempest job for python-tempestconf on a devstack environment with python3 enabled
      for demo users.
    vars:
      aditional_tempestconf_params: "auth.tempest_roles member"
      tempestconf_pip_virtualenv_python: "python3"
      devstack_localrc:
        USE_PYTHON3: true
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # without Swift, c-bak cannot run (in the Gate at least)
        c-bak: false
